<?php
$flash = $this->flashMessenger();

echo $flash->setMessageOpenFormat('<div role="alert"%s>
        <div class="icon"><span class="s7-check"></span></div>
        <div class="message">
            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span
                    aria-hidden="true" class="s7-close"></span></button>
                    <p>')
    ->setMessageSeparatorString('</p><p>')
    ->setMessageCloseString('</p></div></div>')
    ->render('default', ['alert', 'alert-primary', 'alert-icon', 'alert-icon-color', 'alert-dismissible']);

echo $flash->setMessageOpenFormat('<div role="alert"%s>
        <div class="icon"><span class="s7-check"></span></div>
        <div class="message">
            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span
                    aria-hidden="true" class="s7-close"></span></button>
                    <p>')
    ->setMessageSeparatorString('</p><p>')
    ->setMessageCloseString('</p></div></div>')
    ->render('success', ['alert', 'alert-success', 'alert-icon', 'alert-icon-color', 'alert-dismissible']);

echo $flash->setMessageOpenFormat('<div role="alert"%s>
        <div class="icon"><span class="s7-info"></span></div>
        <div class="message">
            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span
                    aria-hidden="true" class="s7-close"></span></button>
                    <p>')
    ->setMessageSeparatorString('</p><p>')
    ->setMessageCloseString('</p></div></div>')
    ->render('info', ['alert', 'alert-info', 'alert-icon', 'alert-icon-color', 'alert-dismissible']);

echo $flash->setMessageOpenFormat('<div role="alert"%s>
        <div class="icon"><span class="s7-attention"></span></div>
        <div class="message">
            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span
                    aria-hidden="true" class="s7-close"></span></button>
                    <p>')
    ->setMessageSeparatorString('</p><p>')
    ->setMessageCloseString('</p></div></div>')
    ->render('warning', ['alert', 'alert-warning', 'alert-icon', 'alert-icon-color', 'alert-dismissible']);

echo $flash->setMessageOpenFormat('<div role="alert"%s>
        <div class="icon"><span class="s7-close-circle"></span></div>
        <div class="message">
            <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span
                    aria-hidden="true" class="s7-close"></span></button>
                    <p>')
    ->setMessageSeparatorString('</p><p>')
    ->setMessageCloseString('</p></div></div>')
    ->render('error', ['alert', 'alert-danger', 'alert-icon', 'alert-icon-color', 'alert-dismissible']);
