<?php if($this->resources === false) $this->resources = [] ?>
<div class="main-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="widget widget-fullwidth widget-small">
                <div class="widget-head">
                    <div class="title">Resources</div>
                </div>
                <table id="table1" class="table table-striped table-hover table-fw-widget">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->resources as $resource) : ?>
                        <tr class="odd gradeX">
                            <td><?= $resource->getId() ?></td>
                            <td><?= $resource->getName() ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>