<?php if ($this->roles === false) $this->roles = [] ?>
<div class="main-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="widget widget-fullwidth widget-small">
                <div class="widget-head">
                    <div class="title">Roles</div>
                </div>
                <table id="table1" class="table table-striped table-hover table-fw-widget">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Parent</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->roles as $role) { ?>
                        <tr class="odd gradeX">
                            <td><?= $role->getId() ?></td>
                            <td><?= $role->getName() ?></td>
                            <td>
                                <?php
                                $parents = $role->getParents();
                                $size    = sizeof($parents);

                                foreach ($parents as $index => $parent) {
                                    echo ($index < $size - 1) ? $parent->getName() . ', ' : $parent->getName();
                                }
                                ?>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>