<?= $this->partial('template/notifications/notifications/sticky') ?>

<div class="main-content">
    <div class="row">
        <div class="col-md-4">
            <div class="widget widget-pie">
                <div class="widget-head"><span class="title">Top Browser</span></div>
                <div class="row chart-container">
                    <div class="col-md-6">
                        <div id="widget-top-1" class="chart"></div>
                    </div>
                    <div class="col-md-6">
                        <div class="legend"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="widget widget-pie">
                <div class="widget-head"><span class="title">Top Platform</span></div>
                <div class="row chart-container">
                    <div class="col-md-6">
                        <div id="widget-top-2" class="chart"></div>
                    </div>
                    <div class="col-md-6">
                        <div class="legend"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="widget widget-pie widget-pie-stats">
                <div class="widget-head"><span class="title">Top City</span></div>
                <div class="row chart-container">
                    <div class="col-md-6">
                        <div id="widget-top-3" class="chart"></div>
                    </div>
                    <div class="col-md-6">
                        <div class="legend"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="row">
                <div class="col-md-12">
                    <div class="widget widget-radar">
                        <div class="widget-head">
                            <span class="title">Page Views</span>
                        </div>
                        <div class="chart-container">
                            <canvas id="radar-chart1" height="180px"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="widget widget-fullwidth line-chart">
                <div class="widget-head">
                    <span class="title">Page Visits</span>
                </div>
                <div class="chart-container">
                    <div id="line-chart1" style="height: 260px;"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="widget widget-calendar">
                <div class="cal-container">
                    <div class="cal-calendar">
                        <div class="ui-datepicker"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12"></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="widget widget-map">
                <div class="widget-head"><span class="title">Global Stats</span></div>
                <div class="map-container">
                    <div id="world-map" style="height: 227px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>