<?php

$form = $this->form;

$form->setAttributes([
    'class' => 'form-horizontal',
    'data-parsley-validate' => '',
    'novalidate' => ''
]);

$form->get('email')->setAttributes([
    'id' => 'email',
    'data-parsley-trigger' => 'change',
    'data-parsley-errors-messages-disabled' => 'true',
    'data-parsley-class-handler' => '#email-handler',
    'autocomplete' => 'off',
    'class' => 'form-control',
    'placeholder' => $this->translate('Your Email')
]);

$form->get('submit')->setAttributes([
    'id' => 'send_btn',
    'data-dismiss' => 'modal',
    'class' => 'btn btn-block btn-primary btn-lg',
    'value' => $this->translate('Reset Password')
]);

$form->prepare();
?>
<div class="am-wrapper am-login">
    <div class="am-content">
        <div class="main-content">
            <div class="login-container forgot-password">
                <div class="panel panel-default">
                    <div class="panel-heading"><img src="<?= $this->basePath('assets/img/logo-full-retina.png') ?>"
                                                    alt="logo" width="150px"
                                                    height="39px"
                                                    class="logo-img"><span><?= $this->translate('Forgot your password?') ?></span>
                    </div>
                    <div class="panel-body">
                        <?= $this->partial('template/alerts/icon-alerts') ?>
                        <?php echo $this->form()->openTag($form); ?>
                        <div class="form-group">
                            <div id="email-handler" class="input-group"><span class="input-group-addon"><i
                                        class="icon s7-mail"></i></span>
                                <?php
                                $element = $form->get('email');
                                echo $this->formElement($element);
                                ?>
                            </div>
                            <?= $this->formElementErrors($element); ?>
                        </div>
                        <p class="contact text-center"><?= $this->translate('Don\'t remember your email?') ?> <a
                                href="#"><?= $this->translate('Contact Support') ?></a>.
                        </p>
                        <?= $this->formRow($form->get('submit')) ?>
                        <?= $this->formRow($form->get('csrf')); ?>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
                <div class="text-center out-links"><a href="#">© <?= date('Y') ?> o0psCMS</a></div>
            </div>
        </div>
    </div>
</div>