<?php

$form = $this->form;

$form->setAttributes(array(
    'data-parsley-validate' => '',
    'novalidate' => '',
    'class' => 'form-horizontal'
));

$form->get('username')->setAttributes(array(
    'class' => 'form-control',
    'data-parsley-trigger' => 'change',
    'data-parsley-errors-messages-disabled' => 'true',
    'data-parsley-class-handler' => '#username-handler',
    'autocomplete' => 'off',
    'placeholder' => $this->translate('Username')
));


$form->get('email')->setAttributes(array(
    'class' => 'form-control',
    'data-parsley-trigger' => 'change',
    'data-parsley-errors-messages-disabled' => 'true',
    'data-parsley-class-handler' => '#email-handler',
    'autocomplete' => 'off',
    'placeholder' => $this->translate('Your Email')
));

$form->get('password')->setAttributes(array(
    'id' => 'password',
    'class' => 'form-control',
    'data-parsley-trigger' => 'change',
    'data-parsley-errors-messages-disabled' => 'true',
    'data-parsley-class-handler' => '#password-handler',
    'autocomplete' => 'off',
    'placeholder' => $this->translate('Password')
));

$form->get('passwordVerify')->setAttributes(array(
    'class' => 'form-control',
    'data-parsley-trigger' => 'change',
    'data-parsley-errors-messages-disabled' => 'true',
    'data-parsley-class-handler' => '#confirm-handler',
    'data-parsley-equalto' => '#password',
    'autocomplete' => 'off',
    'placeholder' => $this->translate('Confirm Password')
));

$form->get('submit')->setAttributes(array(
    'class' => 'btn btn-block btn-primary btn-lg',
    'value' => $this->translate('Sign Up')
));

$form->prepare();
?>

<div class="am-wrapper am-login am-signup">
    <div class="am-content">
        <div class="main-content">
            <div class="login-container sign-up">
                <div class="panel panel-default">
                    <div class="panel-heading"><img src="<?= $this->basePath('assets/img/logo-full-retina.png') ?>"
                                                    alt="logo" width="150px"
                                                    height="39px"
                                                    class="logo-img"><span><?= $this->translate('Please enter your user information.') ?></span>
                    </div>
                    <div class="panel-body">
                        <?= $this->form()->openTag($form); ?>
                        <div class="title"><span><?= $this->translate('Sign up with') ?></span></div>
                        <div class="sign-up-form">
                            <div class="form-group row social-signup">
                                <div class="col-xs-6">
                                    <button type="button" class="btn btn-block btn-social btn-facebook"><i
                                            class="fa fa-facebook icon icon-left"></i> Facebook
                                    </button>
                                </div>
                                <div class="col-xs-6">
                                    <button type="button" class="btn btn-block btn-social btn-twitter"><i
                                            class="fa fa-twitter icon icon-left"></i> Twitter
                                    </button>
                                </div>
                            </div>
                            <div class="title"><span class="title">Or</span></div>
                            <div class="form-group">
                                <div id="username-handler" class="input-group"><span class="input-group-addon"><i
                                            class="icon s7-user"></i></span>
                                    <?php $element = $form->get('username'); ?>
                                    <?= $this->formElement($element) ?>
                                </div>
                                <?= $this->formElementErrors($element) ?>
                            </div>
                            <div class="form-group">
                                <div id="email-handler" class="input-group"><span class="input-group-addon"><i
                                            class="icon s7-mail"></i></span>
                                    <?php $element = $form->get('email'); ?>
                                    <?= $this->formElement($element) ?>
                                </div>
                                <?= $this->formElementErrors($element) ?>
                            </div>
                            <div class="form-group row">
                                <div class="col-xs-6">
                                    <div id="password-handler" class="input-group"><span
                                            class="input-group-addon"><i class="icon s7-lock"></i></span>
                                        <?php $element = $form->get('password'); ?>
                                        <?= $this->formElement($element) ?>
                                    </div>
                                    <?= $this->formElementErrors($element) ?>
                                </div>
                                <div class="col-xs-6">
                                    <div id="confirm-handler" class="input-group"><span class="input-group-addon"><i
                                                class="icon s7-lock"></i></span>
                                        <?php $element = $form->get('passwordVerify'); ?>
                                        <?= $this->formElement($element) ?>
                                    </div>
                                    <?= $this->formElementErrors($element) ?>
                                </div>
                            </div>
                        </div>
                        <p class="conditions"><?= $this->translate('By creating an account, you agree with the ') ?><a
                                href="#"><?= $this->translate('Terms and
                                    Conditions') ?></a>.</p>
                        <?= $this->formRow($form->get('csrf')); ?>
                        <?= $this->formRow($form->get('submit')); ?>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
                <div class="text-center out-links"><a href="#">© <?= date('Y') ?> o0psCMS</a></div>
            </div>
        </div>
    </div>
</div>
