<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta name="description" content="">
    <meta name="author" content="">
    <?= $this->headTitle('o0psCMS')->setSeparator(' | ')->setAutoEscape(false) ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('assets/img/favicon.ico')])
        ->prependStylesheet($this->basePath('assets/css/style.css'))
        ->prependStylesheet($this->basePath('assets/lib/stroke-7/style.css'))
    ?>

    <?= $this->headScript() ?>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="am-splash-screen">

<?= $this->content ?>

<?= $this->inlineScript()
    ->appendFile($this->basePath('assets/lib/jquery/jquery.min.js'))
    ->appendFile($this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'))
    ->appendFile($this->basePath('assets/lib/parsley/parsley.min.js'))
?>

<script type="text/javascript">
    $(document).ready(function () {
        $('form').parsley();
    });
</script>
</body>

</html>