<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">

    <?= $this->headMeta()
             ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
             ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta name="description" content="">
    <meta name="author" content="">

    <?= $this->headTitle('o0psCMS')->setSeparator(' | ')->setAutoEscape(false) ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('assets/img/favicon.ico')])
             ->prependStylesheet($this->basePath('assets/lib/stroke-7/style.css'))
             ->prependStylesheet($this->basePath('assets/lib/jquery.nanoscroller/css/nanoscroller.css'))
             ->appendStylesheet($this->basePath('assets/css/style.css'))
    ?>

    <?= $this->headScript() ?>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="am-wrapper am-fixed-sidebar">

    <?= $this->partial('template/am-top-header.phtml') ?>

    <?= $this->partial('template/am-left-sidebar.phtml') ?>

    <?= $this->partial('template/am-content.phtml', ['content' => $this->content]) ?>

</div>

<?= $this->inlineScript()
         ->prependFile($this->basePath('assets/lib/jquery.nanoscroller/javascripts/jquery.nanoscroller.min.js'))
         ->prependFile($this->basePath('assets/js/main.js'))
         ->prependFile($this->basePath('assets/lib/bootstrap/dist/js/bootstrap.min.js'))
         ->prependFile($this->basePath('assets/lib/jquery/jquery.min.js'))
?>

</body>

</html>