<?php

$form = $this->form;

$form->setAttributes([
    'data-parsley-validate' => '',
    'novalidate'            => '',
    'class'                 => 'form',
]);

$form->get('newPassword')->setAttributes([
    'id'                   => 'newPassword',
    'data-parsley-trigger' => 'change',
    'autocomplete'         => 'off',
    'required'             => true,
    'class'                => 'form-control',
    'placeholder'          => $this->translate('New Password'),
]);

$form->get('newPasswordVerify')->setAttributes([
    'data-parsley-trigger' => 'change',
    'autocomplete'         => 'off',
    'required'             => true,
    'data-parsley-equalto' => '#newPassword',
    'class'                => 'form-control',
    'placeholder'          => $this->translate('Confirm New Password'),
]);

$form->get('currentPassword')->setAttributes([
    'data-parsley-trigger' => 'change',
    'autocomplete'         => 'off',
    'required'             => true,
    'class'                => 'form-control',
    'placeholder'          => $this->translate('Current password'),
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-space btn-primary',
    'value' => $this->translate('Save'),
]);

$form->prepare();
?>
<div class="main-content">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><?= $this->translate('Change Password') ?></h3>
            </div>
            <div class="panel-body">
                <?= $this->partial('template/alerts/icon-alerts') ?>
                <?= $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('newPassword'); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('newPasswordVerify'); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <?php $element = $form->get('currentPassword'); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <?= $this->formRow($form->get('csrf')); ?>
                    <?= $this->formRow($form->get('submit')); ?>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>