<?php

$form = $this->form;

$form->setAttributes([
    'data-parsley-validate' => '',
    'novalidate' => '',
    'class' => 'form'
]);

$form->get('username')->setAttributes([
    'required' => false,
    'readonly' => 'true',
    'class' => 'form-control',
    'placeholder' => $this->translate('Username')
]);

$form->get('email')->setAttributes([
    'required' => false,
    'readonly' => 'true',
    'class' => 'form-control',
    'placeholder' => $this->translate('Email')
]);

$form->get('password')->setAttributes([
    'required' => false,
    'readonly' => 'true',
    'class' => 'form-control',
    'placeholder' => '********'
]);

$form->get('question')->setAttributes([
    'required' => false,
    'readonly' => 'true',
    'class' => 'form-control',
]);

$form->get('firstName')->setAttributes([
    'required' => false,
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter first name')
]);

$form->get('lastName')->setAttributes([
    'required' => false,
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter last name')
]);

$form->get('language')->setAttributes([
    'required' => false,
    'class' => 'form-control select2',
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-space btn-primary',
    'value' => $this->translate('Save')
]);

$form->prepare();
?>
<div class="main-content">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><?= $this->translate('Edit Profile') ?></h3>
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label><?= $this->translate('Username') ?></label>
                            <?php $element = $form->get('username'); ?>
                            <?= $this->formElement($element); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label><?= $this->translate('Email') ?></label>
                            <div class="input-group xs-mb-15">
                                <?php $element = $form->get('email'); ?>
                                <?= $this->formElement($element); ?>
                                <span class="input-group-btn">
                                    <a href="<?= $this->url('o0ps-cms/changeEmail') ?>">
                                        <button type="button" class="btn btn-primary">Change</button>
                                    </a>
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label><?= $this->translate('Password') ?></label>
                            <div class="input-group xs-mb-15">
                                <?php $element = $form->get('password'); ?>
                                <?= $this->formElement($element); ?>
                                <span class="input-group-btn">
                                    <a href="<?= $this->url('o0ps-cms/changePassword') ?>">
                                        <button type="button" class="btn btn-primary">Change</button>
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label><?= $this->translate('Security Question') ?></label>
                            <div class="input-group xs-mb-15">
                                <?php $element = $form->get('question'); ?>
                                <?= $this->formElement($element); ?>
                                <span class="input-group-btn">
                                    <a href="<?= $this->url('o0ps-cms/changeSecurityQuestion') ?>">
                                        <button type="button" class="btn btn-primary">Change</button>
                                    </a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label><?= $this->translate('First Name') ?></label>
                            <?php $element = $form->get('firstName'); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label><?= $this->translate('Last Name') ?></label>
                            <?php $element = $form->get('lastName'); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label><?= $this->translate('Language') ?></label>
                            <?php $element = $form->get('language'); ?>
                            <?= $this->formElement($element); ?>
                            <?= $this->formElementErrors($element); ?>
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <?= $this->formRow($form->get('csrf')); ?>
                    <?= $this->formRow($form->get('submit')); ?>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>