<?php

$form = $this->form;

$form->setAttributes([
    'data-parsley-validate' => '',
    'novalidate' => '',
    'class' => 'form'
]);

$form->get('username')->setAttributes([
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'required' => true,
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter username')
]);

$form->get('firstName')->setAttributes([
    'required' => false,
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter first name')
]);

$form->get('lastName')->setAttributes([
    'required' => false,
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter last name')
]);

$form->get('email')->setAttributes([
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'required' => true,
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter email')
]);

$form->get('password')->setAttributes([
    'id' => 'password',
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'required' => true,
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter password')
]);

$form->get('passwordVerify')->setAttributes([
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'required' => true,
    'data-parsley-equalto' => '#password',
    'class' => 'form-control',
    'placeholder' => $this->translate('Confirm password')
]);

$form->get('language')->setAttributes([
    'required' => true,
    'class' => 'form-control select2',
]);

$form->get('role')->setAttributes([
    'required' => true,
    'class' => 'form-control select2',
]);

$form->get('state')->setAttributes([
    'required' => true,
    'class' => 'form-control select2',
]);

$form->get('question')->setAttributes([
    'required' => true,
    'class' => 'form-control select2',
]);

$form->get('answer')->setAttributes([
    'data-parsley-trigger' => 'change',
    'autocomplete' => 'off',
    'required' => true,
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter answer')
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-space btn-primary',
    'value' => $this->translate('Create User')
]);


$form->prepare();
?>
<div class="main-content">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><?= $this->translate('New User') ?></h3>
            </div>
            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <?php $element = $form->get('username');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('firstName');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('lastName');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <?php $element = $form->get('email');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('password');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('passwordVerify');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <?php $element = $form->get('language');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('role');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('state');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('question');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php $element = $form->get('answer');?>
                            <?= $this->formElement($element);?>
                            <?= $this->formElementErrors($element);?>
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <?= $this->formRow($form->get('csrf'));?>
                    <?= $this->formRow($form->get('submit'));?>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>