<nav class="navbar navbar-default navbar-fixed-top am-top-header">
    <div class="container-fluid">
        <div class="navbar-header">
            <div class="page-title"><span>Dashboard</span></div>
            <a href="#" class="am-toggle-left-sidebar navbar-toggle collapsed"><span
                    class="icon-bar"><span></span><span></span><span></span></span></a><a
                href="<?= $this->url('o0ps-cms') ?>"
                class="navbar-brand"></a>
        </div>
        <a href="#"
           data-toggle="collapse"
           data-target="#am-navbar-collapse"
           class="am-toggle-top-header-menu collapsed"><span
                class="icon s7-angle-down"></span></a>
        <div id="am-navbar-collapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right am-user-nav">
                <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false"
                                        class="dropdown-toggle">
                        <?= $this->gravatar($this->user()->getEmail())->setImgSize(100) ?>
                        <span class="user-name"><?= $this->userDisplayName() ?></span><span
                            class="angle-down s7-angle-down"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="<?= $this->url('o0ps-cms/editProfile') ?>"> <span
                                    class="icon s7-config"></span><?= $this->translate('Settings') ?></a></li>
                        <li><a href="<?= $this->url('o0ps-cms/logout') ?>"> <span
                                    class="icon s7-power"></span><?= $this->translate('Sign Out') ?></a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav am-nav-right">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</nav>